# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_auto_20171120_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_registro',
            field=models.DateTimeField(),
        ),
    ]
